// Developer Express Code Central Example:
// Report Service - how to export or preview a report from code in a WPF application
// 
// 
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=T148944

// Developer Express Code Central Example:
// Report Service - how to export or preview a report from code in a WPF application
// 
// 
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=T148944

// Developer Express Code Central Example:
// Report Service - how to export or print a report from code in a WPF application
// 
// 
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=T258870

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T258870.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
